// <auto-generated />
using System;
using LibraryManagementDLLibrary.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagementDLLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260515060919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PublisherName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookId")
                        .HasName("Book_pk");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Robert Martin",
                            CategoryId = 3,
                            ISBN = "ISBN001",
                            PublishedOn = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherName = "Prentice Hall",
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Andrew Hunt",
                            CategoryId = 3,
                            ISBN = "ISBN002",
                            PublishedOn = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherName = "Addison Wesley",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "J.K Rowling",
                            CategoryId = 1,
                            ISBN = "ISBN003",
                            PublishedOn = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherName = "Bloomsbury",
                            Title = "Harry Potter"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Stephen Hawking",
                            CategoryId = 2,
                            ISBN = "ISBN004",
                            PublishedOn = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherName = "Bantam Books",
                            Title = "Brief History of Time"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "James Clear",
                            CategoryId = 1,
                            ISBN = "ISBN005",
                            PublishedOn = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublisherName = "Penguin",
                            Title = "Atomic Habits"
                        });
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.BookCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("BookCategory_pk");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Fiction",
                            Description = "Fictional books"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Science",
                            Description = "Science related books"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Technology",
                            Description = "Programming and technology books"
                        });
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("CopyStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("BookCopy_PK");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 3,
                            BookId = 2,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 4,
                            BookId = 2,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 5,
                            BookId = 3,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 6,
                            BookId = 3,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            CopyStatus = "Available"
                        },
                        new
                        {
                            Id = 8,
                            BookId = 5,
                            CopyStatus = "Available"
                        });
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("FineSettled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("WasDamagedOnIssue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("Borrowing_PK");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.FinePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("BorrowingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("FinePayment_PK");

                    b.HasIndex("BorrowingId")
                        .IsUnique();

                    b.ToTable("FinePayments");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MemberType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bhargav@gmail.com",
                            IsActive = true,
                            MemberType = "Premium",
                            Name = "Bhargav",
                            PhoneNumber = "9999999991"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rahul@gmail.com",
                            IsActive = true,
                            MemberType = "Basic",
                            Name = "Rahul",
                            PhoneNumber = "9999999992"
                        });
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("UserAccount_PK");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PassWord = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            PassWord = "bhargav123",
                            Role = "Member",
                            Username = "bhargav"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            PassWord = "rahul123",
                            Role = "Member",
                            Username = "rahul"
                        });
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Book", b =>
                {
                    b.HasOne("LibraryManagementModelLibrary.Models.BookCategory", "BookCategory")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Book_CategoryId_FK");

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.BookCopy", b =>
                {
                    b.HasOne("LibraryManagementModelLibrary.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BookCopy_BookId_FK");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Borrowing", b =>
                {
                    b.HasOne("LibraryManagementModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagementModelLibrary.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.FinePayment", b =>
                {
                    b.HasOne("LibraryManagementModelLibrary.Models.Borrowing", "Borrowing")
                        .WithOne("FinePayment")
                        .HasForeignKey("LibraryManagementModelLibrary.Models.FinePayment", "BorrowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FinePayment_BorrowingId_FK");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.UserAccount", b =>
                {
                    b.HasOne("LibraryManagementModelLibrary.Models.Member", "Member")
                        .WithOne()
                        .HasForeignKey("LibraryManagementModelLibrary.Models.UserAccount", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.BookCopy", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Borrowing", b =>
                {
                    b.Navigation("FinePayment");
                });

            modelBuilder.Entity("LibraryManagementModelLibrary.Models.Member", b =>
                {
                    b.Navigation("Borrowings");
                });
#pragma warning restore 612, 618
        }
    }
}
